name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller src/wgrd_cons_parsers/edat.py
    - run: pyinstaller src/wgrd_cons_parsers/ndfbin.py
    - run: pyinstaller src/wgrd_cons_parsers/tgv.py
    - run: pyinstaller src/wgrd_cons_parsers/ppk.py
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*/*.exe
