name: Package Application with Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: PyInstaller Windows EDat
      uses: JackMcKew/pyinstaller-action-windows@python3-10-pyinstaller-5-3
      with:
        path: .
        spec: edat.spec

    - uses: actions/upload-artifact@v2
      with:
        name: edat
        path: dist/edat/
    - uses: actions/upload-artifact@v2
      with:
        name: ndfbin
        path: dist/ndfbin
